// src/types/lesson.type.ts

// Đây là file định nghĩa các interface liên quan đến bài học (Lesson) trong hệ thống.
export interface LessonDto {
  id: string;
  title: string;
  description: string;
  lessonType: string;
  level: string;
  category: string;
  mediaUrl: string;
  audioUrl: string;
  mediaType: string;
  durationSeconds: number;
  thumbnailUrl: string;
  fullTranscript: string;
  hasDictationExercise: boolean;
  availableDictationLevels: string[];
  isPremiumOnly: boolean;
  completionsCount: number;
  avgScore: number;
  tags: string;
  createdAt: string;
  videoId?: string;
  status?: string;
}

// Tham số query cho API Get All
export interface GetLessonsParams {
  page?: number; // Mặc định 1
  pageSize?: number; // 1-100, mặc định 10
  status?: string; // "draft" | "published" | "archived"
  level?: string; // "Beginner" | "Intermediate" | "Advanced" | "Expert"
  type?: string; // "Dictation" | "Shadowing" (Lưu ý: BE dùng field 'type')
  category?: string; // Lọc theo danh mục bài học
  mediaType?: string; // "youtube" | "audio"
  tag?: string; // Lọc theo một tag cụ thể
  search?: string; // Tìm kiếm theo tiêu đề/mô tả
  isPremiumOnly?: boolean; // Lọc bài học phí/miễn phí
}
export interface GetLessonsResponse {
  items: LessonDto[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
}

// Các interface liên quan đến tạo và cập nhật bài học
// ==========================================
// Dùng cho POST /api/admin/lessons/quick-create
// ==========================================
export interface CreateLessonRequest {
  title: string;
  description: string;
  transcript: string;
  format: string;
  mediaUrl: string;
  mediaType: string;
  durationSeconds: number;
  level: string;
  lessonType: string;
  category: string;
  tags: string;
  thumbnailUrl?: string;
}
// ==========================================
// Dùng cho PUT /api/admin/lessons/{id}
// ==========================================
export interface UpdateLessonRequest {
  title?: string;
  description?: string;
  level?: string;
  lessonType?: string;
  tags?: string | null;
  isPremiumOnly?: boolean;
  displayOrder?: number;
  category?: string;
  audioUrl?: string | null;
  mediaUrl?: string | null;
  mediaType?: string | null;
  thumbnailUrl?: string | null;
  fullTranscript?: string;
}
export interface DictationWord {
  text: string;
  isBlank: boolean;
}

// src/types/lesson.type.ts

export interface DictationWord {
  text: string;
  isBlank: boolean;
}

export interface DictationSegmentPreview {
  index?: number;
  startTime: number;
  endTime: number;
  text?: string;
  originalText?: string; // BE mới đổi/thêm trường này chứa full câu gốc
  wordCount?: number;
  words: DictationWord[];
}

export interface DictationWord {
  text: string;
  isBlank: boolean;
  position: number;
  answer?: string; // BE mới thêm vào để lưu từ gốc bị khuyết
  hint?: string; // Có thể có hint trong tương lai
}

export interface DictationPreviewResponse {
  lessonId: string;
  title: string;
  status: string;
  totalSegments: number;
  totalWords: number;
  readyToPublish: boolean;
  publishBlockers: string[];
  segments: DictationSegmentPreview[];
  dictationTemplates?: Record<string, DictationTemplate>;
}

// --- Interface cho API preview bài tập điền từ (Dictation) ---
export interface DictationPreviewResponse {
  lessonId: string;
  title: string;
  status: string;
  totalSegments: number;
  totalWords: number;
  readyToPublish: boolean;
  publishBlockers: string[];
  segments: DictationSegmentPreview[];
}
// --- 4. Các interface liên quan đến cập nhật trạng thái bài học ---
export interface UpdateLessonStatusRequest {
  status: string; // "draft" | "published" | "archived"
}

export interface UpdateLessonStatusResponse {
  lessonId: string;
  title: string;
  previousStatus: string;
  newStatus: string;
  message: string;
}

// --- 5. Interface cho API cập nhật transcript ---
export interface UpdateTranscriptRequest {
  rawContent: string;
  format: "plain" | "vtt" | "srt";
}

export interface UpdateTranscriptResponse {
  lessonId: string;
  segmentCount: number;
  wordCount: number;
  dictationTemplatesRegenerated: boolean;
  message: string;
}

// --- 6. Interface cho API tạo bài học từ YouTube ---
export interface CreateLessonFromYoutubeRequest {
  youTubeUrl: string;
  captionLanguage: string;
  lessonType: string;
  level: string;
  category: string | null;
  isPremiumOnly: boolean;
  displayOrder: number;
  tags: string;
  status: string;
  titleOverride: string | null;
  descriptionOverride: string | null;
}
export interface CreateLessonFromYoutubeResponse {
  lessonId: string;
  title: string;
  videoId: string;
  embedUrl: string;
  durationSeconds: number;
  thumbnailUrl?: string;
  hasCaptions: boolean;
  captionLanguage: string;
  isAutoGeneratedCaptions: boolean;
  captionSegmentCount: number;
  transcriptWordCount: number;
  availableTranscriptLanguages?: string[];
  hasDictationTemplates: boolean;
  status: string;
  message: string;
}

// --- 7. Interface cho API preview thông tin video YouTube trước khi tạo bài học ---
export interface YoutubePreviewResponse {
  videoId: string;
  title: string;
  description: string;
  channelTitle: string;
  durationSeconds: number;
  thumbnailUrl: string;
  embedUrl: string;
  hasCaptions: boolean;
  availableCaptionLanguages: string[];
  suggestedCategory: string;
}

export interface GetYoutubeTranscriptParams {
  url: string;
  preferredLanguage?: string; // Mặc định 'en'
  includeText?: boolean; // Mặc định true
}

export interface YoutubeTranscriptLine {
  text: string;
  start: number;
  duration: number;
}

export interface YoutubeTranscriptResponse {
  lines: YoutubeTranscriptLine[];
  fullText: string;
}

export interface UpdateDictationTemplatesRequest {
  dictationTemplatesJson: string;
}

// ============ USER API TYPES ============

// GET /api/lessons (Public)
export interface GetUserLessonsParams {
  page?: number;
  pageSize?: number;
  level?: string; // "Beginner" | "Intermediate" | "Advanced" | "Expert"
  type?: string; // "Dictation" | "Shadowing"
  category?: string;
  status?: string; // "published" | "draft" | "archived"
}

export interface GetUserLessonsResponse {
  items: LessonDto[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
}

// Dictation Types
export interface DictationWord {
  text: string;
  isBlank: boolean;
  position: number;
  answer?: string;
  hint?: string;
  length?: number;
  punctuation?: string;
}

export interface DictationSegment {
  startTime: number;
  endTime: number;
  originalText: string;
  words: DictationWord[];
}

export interface DictationTemplate {
  level: string;
  blankPercentage: number;
  segments: DictationSegment[];
  totalBlanks: number;
  totalWords: number;
}

export interface GetDictationExerciseResponse {
  lessonId: string;
  title: string;
  description?: string;
  mediaUrl: string;
  audioUrl: string;
  mediaType: string;
  videoId?: string;
  embedUrl?: string;
  durationSeconds: number;
  level: string;
  template: DictationTemplate;
  thumbnailUrl?: string;
}

// Dictation Submit
export interface DictationAnswer {
  segmentIndex: number;
  position: number;
  userInput: string;
}

export interface SubmitDictationRequest {
  level: string;
  answers: DictationAnswer[];
  timeSpentSeconds: number;
}

export interface DictationResult {
  segmentIndex: number;
  position: number;
  isCorrect: boolean;
  userInput: string;
  correctAnswer?: string;
  message?: string;
}

export interface SubmitDictationResponse {
  exerciseId: string;
  score: number;
  totalBlanks: number;
  answeredBlanks: number;
  correctCount: number;
  incorrectCount: number;
  skippedCount: number;
  level: string;
  timeSpentSeconds: number;
  results: DictationResult[];
  feedback?: string;
  // Fields mới từ backend (LESSON_DICTATION_SUBMIT_FE_NOTES.md)
  answeredAccuracy: number; // % đúng trên số blank user đã submit
  isSubmissionComplete: boolean; // true khi user đã điền đủ toàn bộ blank
  isFullyCorrect: boolean; // true khi toàn bộ blank của bài đều đúng
}

export interface TimedSegment {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
  wordCount?: number;
  isCompleted?: boolean;
  bestScore?: number | null;
  attempts?: number | null;
}

export interface LevelConfig {
  level: string;
  showTranscriptBefore: boolean;
  showTranscriptAfter: boolean;
  maxReplays: number; // -1 = unlimited
  showWordCount?: boolean;
}

export interface GetSegmentsResponse {
  lessonId: string;
  title?: string;
  description?: string;
  audioUrl?: string;
  mediaType?: string;
  durationSeconds?: number;
  thumbnailUrl?: string;
  isPremiumOnly?: boolean;
  level: string;
  segments: TimedSegment[];
  levelConfig: LevelConfig;
  completedCount?: number;
  progressPercent?: number;
  totalSegments?: number;
}

// Segment Check
// ==========================================
// SHARED TYPES (Dùng chung cho cả 2 phần)
// ==========================================
export interface WordComparison {
  word: string;
  isCorrect: boolean;
  expected?: string;
}

// ==========================================
// SHADOWING: Check Segment (Gõ text thay thế Voice)
// ==========================================
export interface CheckShadowingSegmentRequest {
  level: string;
  userText: string;
  timeSpentSeconds: number;
}

export interface CheckShadowingSegmentResponse {
  segmentIndex: number;
  transcript: string;
  userText: string;
  words: WordComparison[];
  accuracy: number; // Điểm 0-100
  feedback?: string;
}

// ==========================================
// SHADOWING: Check Voice (Nhận diện giọng nói STT)
// ==========================================
export interface CheckVoiceRequest {
  level: string;
  spokenText: string;
  speechConfidence: number;
  timeSpentSeconds: number;
}

export interface CheckVoiceResponse {
  spokenText: string;
  speechConfidence: number;
  passThreshold: number;
  isPassed: boolean;
  segmentIndex: number;
  accuracy: number;
  correctCount: number;
  totalWords: number;
  wrongCount: number;
  skippedCount: number;
  transcript: string;
  wordResults: {
    word: string;
    status: string;
    userTyped: string | null;
  }[];
  feedback?: string;
}

// ==========================================
// DICTATION: Check Segment (Chấm điểm từng câu Dictation)
// ==========================================
export interface CheckDictationSegmentRequest {
  level: string;
  userText: string; // Hoặc bạn có thể đổi thành mảng answers tùy BE yêu cầu
  timeSpentSeconds: number;
}

export interface CheckDictationSegmentResponse {
  segmentIndex: number;
  transcript: string;
  userText: string;
  words: WordComparison[]; // Tái sử dụng interface WordComparison ở trên
  accuracy: number;
  feedback?: string;
}

// ==========================================
// AUDIO & GAMIFICATION INTEGRATION
// ==========================================
export interface CompletedSegment {
  segmentIndex: number;
  bestScore: number;
  attempts: number;
}

export interface MyProgressResponse {
  lessonId: string;
  lessonTitle: string;
  totalSegments: number;
  completedCount: number;
  progressPercent: number;
  status: string; // "NotStarted" | "InProgress" | "Completed"
  lastSegmentIndex: number;
  level?: string;
  completedAt: string | null;
  completedSegments: CompletedSegment[];
}

export interface LessonHistoryItem {
  lessonId: string;
  title: string;
  level: string;
  status: string;
  completedSegments: number;
  avgScore: number;
  bestScore: number;
  startedAt: string;
  progressPercent?: number;
  isPremiumOnly?: boolean;
}

export interface LessonHistoryResponse {
  items: LessonHistoryItem[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
}
